name: futebola_frontend
description: "A new Flutter project futebola."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.2.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_ui_auth: ^1.16.0
  cloud_firestore: ^5.5.1
  provider: ^6.1.2
  google_sign_in: ^6.2.2
  firebase_ui_oauth_google: ^1.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/dash.png
    - assets/codelab.png
    - assets/flutterfire_300x.png

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf